[package]
name = "solana-grinder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.11.5"
num_cpus = "1.13.1"
rayon = "1.5.3"